language: node_js
node_js:
  - "7"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script:
  - yarn global add gulp
  - yarn global add standard
  - yarn
script:
  - yarn build
  - yarn test